### ISSUE TITLE
Docker Composition Fails on CentOS

### ISSUE THREAD

**Issue by gesaleh** [absmach/magistrala#67]
```

[root@samgps mainflux]# docker-compose up
Starting mainflux-mongodb
Starting mainflux-emqttd
Starting mainflux-server
Attaching to mainflux-emqttd, mainflux-mongodb, mainflux-server
mainflux-server    | panic: Network Error : dial tcp [::1]:1883: getsockopt: connection refused
mainflux-server    |
mainflux-server    | goroutine 1 [running]:
mainflux-mongodb   | 2016-10-17T14:52:18.119+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=18a7c813e3d5
mainflux-mongodb   | 2016-10-17T14:52:18.119+0000 I CONTROL  [initandlisten] db version v3.2.10
mainflux-mongodb   | 2016-10-17T14:52:18.119+0000 I CONTROL  [initandlisten] git version: 79d9b3ab5ce20f51c272b4411202710a082d0317
mainflux-mongodb   | 2016-10-17T14:52:18.119+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mainflux-server    | panic(0x701f40, 0xc420166e60)
mainflux-mongodb   | 2016-10-17T14:52:18.119+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mainflux-server    |    /usr/local/go/src/runtime/panic.go:500 +0x1a1
mainflux-mongodb   | 2016-10-17T14:52:18.119+0000 I CONTROL  [initandlisten] modules: none
mainflux-server    | github.com/mainflux/mainflux/clients.(*MqttConn).MqttSub(0xc42013dee0)
mainflux-mongodb   | 2016-10-17T14:52:18.119+0000 I CONTROL  [initandlisten] build environment:
mainflux-server    |    /go/src/github.com/mainflux/mainflux/clients/mqtt_client.go:61 +0x322
mainflux-mongodb   | 2016-10-17T14:52:18.120+0000 I CONTROL  [initandlisten]     distmod: debian81
mainflux-server    | main.main()
mainflux-mongodb   | 2016-10-17T14:52:18.120+0000 I CONTROL  [initandlisten]     distarch: x86_64
mainflux-server    |    /go/src/github.com/mainflux/mainflux/main.go:126 +0x928
mainflux-mongodb   | 2016-10-17T14:52:18.120+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mainflux-mongodb   | 2016-10-17T14:52:18.120+0000 I CONTROL  [initandlisten] options: { storage: { journal: { enabled: false }, mmapv1: { smallFiles: true } } }
mainflux-mongodb   | 2016-10-17T14:52:18.139+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mainflux-mongodb   | 2016-10-17T14:52:18.139+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=13G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),,log=(enabled=false),
mainflux-mongodb   | 2016-10-17T14:52:18.351+0000 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
mainflux-mongodb   | 2016-10-17T14:52:18.351+0000 I CONTROL  [initandlisten]
mainflux-mongodb   | 2016-10-17T14:52:18.351+0000 I CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
mainflux-mongodb   | 2016-10-17T14:52:18.351+0000 I CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
mainflux-mongodb   | 2016-10-17T14:52:18.351+0000 I CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]
mainflux-mongodb   | 2016-10-17T14:52:18.352+0000 I CONTROL  [initandlisten]
mainflux-mongodb   | 2016-10-17T14:52:18.352+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
mainflux-mongodb   | 2016-10-17T14:52:18.352+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mainflux-mongodb   | 2016-10-17T14:52:18.352+0000 I CONTROL  [initandlisten]
mainflux-mongodb   | 2016-10-17T14:52:18.352+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
mainflux-mongodb   | 2016-10-17T14:52:18.352+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mainflux-mongodb   | 2016-10-17T14:52:18.352+0000 I CONTROL  [initandlisten]
mainflux-mongodb   | 2016-10-17T14:52:18.353+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mainflux-mongodb   | 2016-10-17T14:52:18.353+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
mainflux-mongodb   | 2016-10-17T14:52:18.354+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mainflux-mongodb   | 2016-10-17T14:52:18.476+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.4:33071 #1 (1 connection now open)
mainflux-mongodb   | 2016-10-17T14:52:18.495+0000 I NETWORK  [conn1] end connection 172.17.0.4:33071 (0 connections now open)
mainflux-server exited with code 2
mainflux-emqttd    | emqttd is started successfully!
mainflux-emqttd    | emqttd_auth_http
mainflux-emqttd    | RPC to 'emqttd@127.0.0.1' failed: {'EXIT',
mainflux-emqttd    |                                    {badarg,
mainflux-emqttd    |                                     [{ets,match,
mainflux-emqttd    |                                       [mqttd_ctl_cmd,{{'_',plugins},'$1','_'}],
mainflux-emqttd    |                                       []},
mainflux-emqttd    |                                      {emqttd_ctl,lookup,1,
mainflux-emqttd    |                                       [{file,"src/emqttd_ctl.erl"},{line,78}]},
mainflux-emqttd    |                                      {emqttd_ctl,run,1,
mainflux-emqttd    |                                       [{file,"src/emqttd_ctl.erl"},{line,70}]},
mainflux-emqttd    |                                      {rpc,'-handle_call_call/6-fun-0-',5,
mainflux-emqttd    |                                       [{file,"rpc.erl"},{line,206}]}]}}
mainflux-emqttd exited with code 1
```

**Comment by drasko** [comment]
EMQTTD starts slowly. Even though it is fired-up before `mainflux-core` server, it takes some time to turn on.

`mainflux-core` service should wait for EMQTTD service to be present. This can be done via [dockerize](https://github.com/jwilder/dockerize) or [wait-for-it](https://github.com/vishnubob/wait-for-it)

**Comment by drasko** [comment]
Fixed by https://github.com/mainflux/mainflux/commit/6b54d38d53c0d93b4ffd0b1ddad853c9f17914d8
