### ISSUE TITLE
Error during make docker_mqtt

### ISSUE THREAD

**Issue by tdestro** [absmach/magistrala#846]
```
[mainflux]$ make docker_mqtt

# MQTT Docker build must be done from root dir because it copies .proto files
docker build --tag=mainflux/mqtt-amd64 -f mqtt/aedes/Dockerfile .
Sending build context to Docker daemon  142.7MB
Step 1/5 : FROM node:10.15.1-alpine
 ---> fe6ff768f798
Step 2/5 : COPY *.proto mqtt/* ./
 ---> 01fae65c0e77
Step 3/5 : RUN npm rebuild && npm install
 ---> Running in cd22b74cd621

> protobufjs@6.8.8 postinstall /node_modules/protobufjs
> node scripts/postinstall


> grpc@1.23.3 install /node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
[grpc] Success: "/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-musl/grpc_node.node" is installed via remote

> dtrace-provider@0.8.8 install /node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 5.2.11-arch1-1-ARCH
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/dtrace-provider
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
2@1.0.2 /node_modules/2
...
ansi-regex@3.0.0 /node_modules/eslint/node_modules/ansi-regex
audited 1005 packages in 2.328s
found 0 vulnerabilities

Removing intermediate container cd22b74cd621
 ---> c054ef48af75
Step 4/5 : EXPOSE 1883 8880
 ---> Running in 0b44cc53ab3f
Removing intermediate container 0b44cc53ab3f
 ---> 1358101abda4
Step 5/5 : CMD ["node", "mqtt.js"]
 ---> Running in a759e6907142
Removing intermediate container a759e6907142
 ---> 0ea21c2fe6b2
Successfully built 0ea21c2fe6b2
Successfully tagged mainflux/mqtt-amd64:latest
`
```

**Comment by tdestro** [comment]
Suggestion to fix, Add to mqtt/aedes/Dockerfile:
RUN apk --no-cache add --virtual builds-deps build-base python
.....
.....
RUN apk del builds-deps

**Comment by nwneisen** [comment]
I'm interested in doing a PR for this issue.

**Comment by nwneisen** [comment]
It looks like @blokovi already took care of it.  Perhaps I can take a look at the ARM image?

**Comment by drasko** [comment]
Hi @nwneisen no need for now, we have some re-architecturing to do for ARM images now as we move towards VerneMQ.

There are some more urgent issues, if you want to help?

**Comment by nwneisen** [comment]
Hi @drasko,

I'd love to help.  I'm looking through other issues now.  Suggestions for urgent issues would be great.

**Comment by drasko** [comment]
@nwneisen would you like to play with Jaeger and OpenTracing: https://github.com/mainflux/mainflux/issues/787

Instrumenting is a great stuff, and would highly improve Mainflux.

Apart for this, for going a bit deeper in the core I would suggest: https://github.com/mainflux/mainflux/issues/484

This one looks trivial, but there is some work to be put, as it spans through whole devops configs: https://github.com/mainflux/mainflux/issues/512

@nmarcetic suggestions?

Otherwise, ping us on [Gitter](https://gitter.im/Mainflux/mainflux), so we can allocate the one nice issue for you.

Thanks a lot for your wish to give us a hand! Highly appreciated!

**Comment by nwneisen** [comment]
Thanks @drasko!
