### ISSUE TITLE
Manager errors on existing user e-mail

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#96]
**BUG REPORT**

1. What were you trying to achieve?
Create user

2. What are the expected results?
Location header with user UUID

3. What are the received results?

```
drasko@Marx:~/go/src/github.com/mainflux/mainflux/cmd/manager$ go run main.go 
{"start":"manager","ts":"2017-09-24T02:08:36.020454561Z"}
{"http_port":8180,"ts":"2017-09-24T02:08:36.036257545Z"}
{"email":"john.doe@email.com","error":"email already taken","method":"register","took":"96.534049ms","ts":"2017-09-24T02:09:36.875275927Z"}
2017/09/24 04:09:36 http: panic serving [::1]:58866: inconsistent label cardinality
goroutine 45 [running]:
net/http.(*conn).serve.func1(0xc420206000)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x783b20, 0xc42007ee50)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/mainflux/mainflux/vendor/github.com/prometheus/client_golang/prometheus.(*MetricVec).With(0xc4201868c0, 0xc42017ab70, 0xc4201923e8, 0x0)
	/home/drasko/go/src/github.com/mainflux/mainflux/vendor/github.com/prometheus/client_golang/prometheus/vec.go:146 +0x76
github.com/mainflux/mainflux/vendor/github.com/prometheus/client_golang/prometheus.(*CounterVec).With(0xc42017c038, 0xc42017ab70, 0x2, 0xc42017ab70)
	/home/drasko/go/src/github.com/mainflux/mainflux/vendor/github.com/prometheus/client_golang/prometheus/counter.go:145 +0x38
github.com/mainflux/mainflux/vendor/github.com/go-kit/kit/metrics/prometheus.(*Counter).Add(0xc4201a4f00, 0x3ff0000000000000)
	/home/drasko/go/src/github.com/mainflux/mainflux/vendor/github.com/go-kit/kit/metrics/prometheus/prometheus.go:45 +0x5c
github.com/mainflux/mainflux/manager/api.(*metricService).Register.func1(0xc42017a330, 0xbe69e2d82e6aa02f, 0xe25929963, 0xa13440)
	/home/drasko/go/src/github.com/mainflux/mainflux/manager/api/metrics.go:30 +0xb9
github.com/mainflux/mainflux/manager/api.(*metricService).Register(0xc42017a330, 0xc4201e8240, 0x12, 0xc4201806f0, 0x3, 0x9d5fc0, 0xc42007f340)
	/home/drasko/go/src/github.com/mainflux/mainflux/manager/api/metrics.go:34 +0xcf
github.com/mainflux/mainflux/manager/api.registrationEndpoint.func1(0x9dc740, 0xc420186e80, 0x7a7000, 0xc4201a4d80, 0xc4201a4d80, 0x0, 0x0, 0x7c2f40)
	/home/drasko/go/src/github.com/mainflux/mainflux/manager/api/endpoint.go:13 +0x73
github.com/mainflux/mainflux/vendor/github.com/go-kit/kit/transport/http.Server.ServeHTTP(0xc420174900, 0x819d78, 0x819d98, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x819d90, ...)
	/home/drasko/go/src/github.com/mainflux/mainflux/vendor/github.com/go-kit/kit/transport/http/server.go:108 +0x338
github.com/mainflux/mainflux/vendor/github.com/go-kit/kit/transport/http.(*Server).ServeHTTP(0xc42014ed90, 0x9dbf80, 0xc4201840e0, 0xc4201b8b00)
	<autogenerated>:1 +0x94
github.com/mainflux/mainflux/vendor/github.com/go-zoo/bone.(*Route).parse(0xc4200a15e0, 0x9dbf80, 0xc4201840e0, 0xc4201b8b00, 0xc4200ce8c8)
	/home/drasko/go/src/github.com/mainflux/mainflux/vendor/github.com/go-zoo/bone/route.go:148 +0x119
github.com/mainflux/mainflux/vendor/github.com/go-zoo/bone.(*Mux).parse(0xc4201728a0, 0x9dbf80, 0xc4201840e0, 0xc4201b8b00, 0x7e6280)
	/home/drasko/go/src/github.com/mainflux/mainflux/vendor/github.com/go-zoo/bone/helper.go:18 +0xb9
github.com/mainflux/mainflux/vendor/github.com/go-zoo/bone.(*Mux).ServeHTTP(0xc4201728a0, 0x9dbf80, 0xc4201840e0, 0xc4201b8b00)
	/home/drasko/go/src/github.com/mainflux/mainflux/vendor/github.com/go-zoo/bone/bone.go:43 +0x4d
net/http.serverHandler.ServeHTTP(0xc4202025b0, 0x9dbf80, 0xc4201840e0, 0xc4201b8b00)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420206000, 0x9dc740, 0xc420186d80)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

4. What are the steps to reproduce the issue?
```
curl -s -S -i -X POST -H "Content-Type: application/senml+json" localhost:8180/users -d '{"email":"john.doe@email.com", "password":"123"}'
```

**Comment by mijicd** [comment]
Resolved by #97 .
